### ISSUE TITLE
Error creating alert

### ISSUE THREAD

**Issue by juanpablobr** [CERT-BDF/TheHive4py#15]
### Request Type
Bug 

### Problem Description
API doesn't found Alert, AlertArtifacts in model

### Steps to Reproduce
If you try to run the sample to create alert, it exits with an error.

![image](https://cloud.githubusercontent.com/assets/19836161/26164131/54111a98-3af1-11e7-82d5-52b7d5527c28.png)

**Comment by To-om** [comment]
Hi @juanpablobr,

I think that you have an old version of thehive4py. Please ensure you got the latest version. Alerts have been added in version 1.2.0.
