### ISSUE TITLE
certificate verify option not included in create_case_task

### ISSUE THREAD

**Issue by armngar** [CERT-BDF/TheHive4py#27]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Docker
| OS version (client)       | Ubuntu
| TheHive4py version / git hash   |  512af3a  

### Problem Description
In line 67 of api.py, the option to specify certificate validation isn't included.

### Steps to Reproduce
Attempt to disable certificate validation and then call create_case_task

### Possible Solutions
 return requests.post(req, headers={'Content-Type': 'application/json'}, data=data, proxies=self.proxies, auth=self.auth, verify=self.cert,)

### Complementary information
N/A

**Comment by armngar** [comment]
I see another similar bug on line 87 as well

**Comment by billmurrin** [comment]
FYI, I added a pull request to address this issue.
https://github.com/CERT-BDF/TheHive4py/pull/28

**Comment by nadouani** [comment]
Yes this has been fixed by https://github.com/CERT-BDF/TheHive4py/pull/28

Thanks
