### ISSUE TITLE
Case model is missing the required `status` attribute

### ISSUE THREAD

**Issue by Rolinh** [CERT-BDF/TheHive4py#29]
### Request Type

Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| TheHive4py version  |  1.2.3

### Problem Description

As specified [in the documentation](https://github.com/CERT-BDF/TheHiveDocs/blob/master/api/case.md#model-definition), the Case model has a required `status` attribute which can take any value in [`Open`, `Resolved`, `Deleted`] with `Open` as the default.

The Case model in TheHive4py does not have such attribute. As a consequence, when instantiating a new Case from JSON data as returned by the API, the status attribute is discarded.

### Steps to Reproduce

Instantiate a Case object with a case in its JSON form as produced by TheHive API (2.12.1) (`thehive.api.models.Case(json=case_as_json)`).

**Comment by nadouani** [comment]
The `status` field should in fact be marked as *Read Only* on the documentation page. This field should not be updated manually.

Thanks for finding this inconsistency

**Comment by nadouani** [comment]
Documentation has been updated
