### ISSUE TITLE
Allow specifying range to return > 10 cases, observables, etc.,

### ISSUE THREAD

**Issue by BrevilleBro** [CERT-BDF/TheHive4py#30]
### Request Type
Feature Request

### Problem Description
TheHive returns the 10 first elements (case, task, observable, ...). In the REST API you can specify the number of element you want using the parameter range (eg. "0-40"). Currently, you can't provide this parameter to TheHive4py.

**Comment by nadouani** [comment]
Yes this is correct, except for case search that allows specifying a `range` and a `sort` in addition to the `query` parameter.

I'll add 3 options options to the following methods:
- get_case_observables
- get_case_tasks
