### ISSUE TITLE
Add a find_alerts method to search for alerts

### ISSUE THREAD

**Issue by nadouani** [CERT-BDF/TheHive4py#31]
### Request Type
Feature Request

### Problem Description
The goal here is to provide a function to search for alerts. This function should accept the following options: `query`, `range` and `sort` like the *find_cases* function

**Comment by nadouani** [comment]
This is a usage example:

```python
import json
from thehive4py.api import TheHiveApi

# Instanciate an API client
api = TheHiveApi('http://127.0.0.1:9000', 'username', 'password', {})

# Build the query that returns the Alerts with medium severity of type "siem"
query = {
    "_and": [
        {"type": "siem"},
        {"severity": 2}
    ]
}

# Call the alert find function
siem_alerts = api.find_alerts(query=query)

# Display the response
print(json.dumps(siem_alerts.json(), indent=4))
```

**Comment by Marsidi** [comment]
Hello,
I am trying to make a query on alerts like this:

from thehive4py.api import TheHiveApi, Eq
from thehive4py.query import And, Between

api = TheHiveApi('http://127.0.0.1:9000', 'username', 'password', {})
sts = Eq('status', 'Ignored')
between = Between("startDate", '1570485600000', '1570572000000')
query = And(sts, between)
alerts = api.find_alerts(query=query)
response = json.loads(alerts.text)

But i get empty response list.
If i remove 'between' from query it works but i need the alerts between two dates.
PS:In this way is working perfectly to find the cases

**Comment by b00lpy** [comment]
Guys, this library is still not working well..
I'm searching alerts by title
`query=Eq("title","My alert title copy and pasted")`

It should return at least one alert but this is not working...

Any suggestion?
