### ISSUE TITLE
Add support of custom fields to the case model

### ISSUE THREAD

**Issue by nadouani** [CERT-BDF/TheHive4py#39]
### Request Type
Feature Request

### Problem Description
TheHive added support to case custom fields, but TheHive4Py didn't allow setting this attribute. We need to enhance the Case model class to support providing custom fields

The custom fields should also be available on the CaseTemplate class

**Comment by billmurrin** [comment]
I just did this [here](https://github.com/billmurrin/TheHive4py/commit/cf53c48ff661fc5c70be9bba346cb3efdd33e725) but didn't issue a PR since it might include another merge for the get_task_logs method that I have the open PR for. If you can use this, please feel free.

**Comment by nadouani** [comment]
Thanks @billmurrin. The issue with custom fields is the required structure. In a case, we need to provide custom fields data with the following format:

```
{
    "booleanField": {
        "boolean": true,
        "order": 0
    },
    "businessImpact": {
        "order": 1,
        "string": "HIGH"
    },
    "cvss": {
        "number": 9,
        "order": 3
    },
    "occurDate": {
        "date": 1512054889000,
        "order": 2
    }
}
```
We need to keep the order (used to display the fields on the right order, and the field's type.

I'll create a helper class to allow easy creation of custom fields. Example:

```
# Prepare the custom fields
customFields = CustomFieldHelper()\
    .add_boolean('booleanField', True)\
    .add_string('businessImpact', 'HIGH')\
    .add_date('occurDate', int(time.time())*1000)\
    .add_number('cvss', 9)\
    .build()

case = Case(title='From TheHive4Py',            
            description='N/A',
            customFields=customFields)
```
