### ISSUE TITLE
Run Cortex analyzer through api

### ISSUE THREAD

**Issue by alexgoedeke** [CERT-BDF/TheHive4py#40]
### Request Type
Question/Feature Request

### Problem Description
Is it possible to run an Cortex analyzer with an given observableID from a python script?

**Comment by nadouani** [comment]
Hello @alexgoedeke 

What's the idea? do you want just to run analyzers on a given observable and just get it's report or, you want to have the report on TheHive?

Cortex has it own python library which is [Cortex4Py](https://github.com/CERT-BDF/Cortex4py) but this will not add any data to TheHive.

That said, we can add the capability to run a job on a given observable, from TheHive.

**Comment by alexgoedeke** [comment]
@nadouani Yes I need the results in TheHive

**Comment by nadouani** [comment]
Se we have to add some methods to make that possible. Good feature request.

**Comment by nadouani** [comment]
Here is doc for how TheHive launches Cortex analyzers: https://github.com/CERT-BDF/TheHiveDocs/tree/master/api/connectors/cortex 

Thanks to @srilumpa

**Comment by alexgoedeke** [comment]
@nadouani I have added the functionality to the API
