### ISSUE TITLE
Error updating case

### ISSUE THREAD

**Issue by npratley** [CERT-BDF/TheHive4py#51]
Have just noticed that in #50 I seem to have broken case creation. The test-case-create.py script fails with:

ko: 400/{"tableName":"case","type":"AttributeCheckingError","errors":[[{"name":"case.updatedAt","value":{"type":"JsonInputValue","value":null},"type":"UnknownAttributeError","message":"Unknown attribute case.updatedAt: {\"type\":\"JsonInputValue\",\"value\":null}"},{"name":"case.caseId","value":{"type":"JsonInputValue","value":null},"type":"UnknownAttributeError","message":"Unknown attribute case.caseId: {\"type\":\"JsonInputValue\",\"value\":null}"},{"name":"case.id","value":{"type":"JsonInputValue","value":null},"type":"UnknownAttributeError","message":"Unknown attribute case.id: {\"type\":\"JsonInputValue\",\"value\":null}"},{"name":"case.createdAt","value":{"type":"JsonInputValue","value":null},"type":"UnknownAttributeError","message":"Unknown attribute case.createdAt: {\"type\":\"JsonInputValue\",\"value\":null}"},{"name":"case.createdBy","value":{"type":"JsonInputValue","value":null},"type":"UnknownAttributeError","message":"Unknown attribute case.createdBy: {\"type\":\"JsonInputValue\",\"value\":null}"},{"name":"case.updatedBy","value":{"type":"JsonInputValue","value":null},"type":"UnknownAttributeError","message":"Unknown attribute case.updatedBy: {\"type\":\"JsonInputValue\",\"value\":null}"}]]}

Sorry @nadouani I didn't run the test scripts before submitting the change.

Rather than setting these attributes to None it may be best to only add the attributes if they exist in the 'json' parameter, or modify `create_case` to exclude them. I can fix that up.

**Comment by nadouani** [comment]
No problem, I'll revert back the changes made on #50
